export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/hall/index',
    'pages/pet-center/index',
    'pages/post-modal/index',
    'pages/marketplace/index',
    'pages/profile/index',
    'pages/friends/index',
  ],
  subPackages: [
    {
      root: 'pages/sub-pages/',
      pages: [
        'ai-assistant/index',
        'memorial-hall/index',
        'create-pet/index',
        'edit-avatar/index',
        'health-records/index',
        'vip-membership/index',
        'product-detail/index',
        'pet-story/index',
        'create-post/index',
        'create-product/index',
        'cart/index',
        'orders/index',
        'wallet/index',
        'settings/index',
        'pet-identity/index',
        'rank/index',
        'feed-detail/index',
        'search/index',
        'timeline/index',
        'help/index',
        'about/index',
        'album/index',
        'chat/index',
        'messages/index',
        'my-posts/index',
        'my-records/index',
        'user-feed/index',
      ],
    },
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#FFF8F3',
    navigationBarTitleText: 'PawLife',
    navigationBarTextStyle: 'black',
  },
  permission: {
    'scope.userLocation': {
      desc: '你的位置信息将用于展示附近宠友的距离',
    },
  },
  requiredPrivateInfos: ['getLocation'],
  tabBar: {
    color: '#9B958E',
    selectedColor: '#FF7A59',
    backgroundColor: '#FFFFFF',
    borderStyle: 'white',
    custom: true,
    list: [
      {
        pagePath: 'pages/hall/index',
        text: '大厅',
        iconPath: 'assets/tabbar/home.png',
        selectedIconPath: 'assets/tabbar/home.png',
      },
      {
        pagePath: 'pages/pet-center/index',
        text: '宠物馆',
        iconPath: 'assets/tabbar/paw.png',
        selectedIconPath: 'assets/tabbar/paw.png',
      },
      {
        pagePath: 'pages/marketplace/index',
        text: '集市',
        iconPath: 'assets/tabbar/shop.png',
        selectedIconPath: 'assets/tabbar/shop.png',
      },
      {
        pagePath: 'pages/friends/index',
        text: '宠友广场',
        iconPath: 'assets/tabbar/paw.png',
        selectedIconPath: 'assets/tabbar/paw.png',
      },
      {
        pagePath: 'pages/profile/index',
        text: '我的',
        iconPath: 'assets/tabbar/user.png',
        selectedIconPath: 'assets/tabbar/user.png',
      },
    ],
  },
});
